// Generated by blueprinter_typescript_models
// Do not edit this file directly

import type { Post } from "./Post";

export interface AdminUser {
  id: number;
  admin: boolean | null;
  bio: string | null;
  email: string | null;
  last_login_at: Date | null;
  name: string;
  settings: Record<string, unknown> | null;
  super_admin: unknown;
  tags: string[] | null;
  posts: Post[];
}
